DROP DATABASE IF EXISTS q2bank

CREATE DATABASE q2bank;

USE q2bank;

CREATE TABLE USUARIOS(
    ID      INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NOME    VARCHAR(50) NOT NULL,
    TIPO    ENUM('lojista', 'comum'),
    CPF     VARCHAR(50) UNIQUE,
    CNPJ    VARCHAR(50) UNIQUE,
    EMAIL   VARCHAR(50) NOT NULL,
    SENHA   VARCHAR(50) NOT NULL,
    SALDO   FLOAT(10.2) NOT NULL
);

/*EATE TABLE TRANSACOES(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    VALOR FLOAT (10.2) NOT NULL,
    DIA DATE NOT NULL,
    HORA TIME NOT NULL
);
*/

--INSERT INTO TRANSACOES  (VALOR, DIA, HORA) VALUES (1000.0, SELECT CURDATE(), SELECT CURTIME())

INSERT INTO USUARIOS (NOME, TIPO, CPF, CNPJ, EMAIL, SENHA, SALDO) VALUES ('ANDERSON', 'comum', '123.123.123-90', '', 'anderson@gmail.com', '123456', 200.10);
INSERT INTO USUARIOS (NOME, TIPO, CPF, CNPJ, EMAIL, SENHA, SALDO) VALUES ('MARIA', 'comum', '444.123.123-90', '', 'maria@gmail.com', '444444', 800.10);


