DROP DATABASE IF EXISTS q2bank;

CREATE DATABASE q2bank;

USE q2bank;

CREATE TABLE USERS(
    ID      INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NAME_USER    VARCHAR(50) NOT NULL,
    TYPE_USER    ENUM('lojista', 'comum'),
    CPF_CNPJ       VARCHAR(50) UNIQUE,
    EMAIL   VARCHAR(50) UNIQUE NOT NULL,
    PASSWORD_USER   VARCHAR(50) NOT NULL,
    WALLET   FLOAT(10.2) NOT NULL
);

CREATE TABLE TRANSACTIONS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    AMOUNT FLOAT (10.2) NOT NULL,
    ID_ORIGIN   INT NOT NULL,
    ID_DEST INT NOT NULL,
    DATE_TIME DATETIME NOT NULL
);

ALTER TABLE TRANSACTIONS
ADD FOREIGN KEY (ID_ORIGIN) REFERENCES USERS(ID);

ALTER TABLE TRANSACTIONS
ADD FOREIGN KEY (ID_DEST) REFERENCES USERS(ID);

INSERT INTO USERS (NAME_USER, TYPE_USER, CPF_CNPJ, EMAIL, PASSWORD_USER, WALLET) VALUES ('ANDERSON', 'comum', '123.123.123-90','anderson@gmail.com', '123456', 200.10);
INSERT INTO USERS (NAME_USER, TYPE_USER, CPF_CNPJ, EMAIL, PASSWORD_USER, WALLET) VALUES ('MARIA', 'comum', '444.123.123-90', 'maria@gmail.com', '444444', 800.10);
INSERT INTO USERS (NAME_USER, TYPE_USER, CPF_CNPJ, EMAIL, PASSWORD_USER, WALLET) VALUES ('ROBERTO', 'lojista', '444.123.988-90', 'roberto@hotmail.com', 'robertinho', 3000);

INSERT INTO TRANSACTIONS (Amount, ID_ORIGIN, ID_DEST, DATE_TIME) VALUES (1000.12, 1, 2, '2022-06-23 00:16:12');

