DROP DATABASE IF EXISTS q2bank;

CREATE DATABASE q2bank;

USE q2bank;

CREATE TABLE USERS(
    ID      INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NAME_USER    VARCHAR(50) NOT NULL,
    TYPE_USER    ENUM('lojista', 'comum'),
    CPF     VARCHAR(50) UNIQUE,
    CNPJ    VARCHAR(50) UNIQUE,
    EMAIL   VARCHAR(50) UNIQUE NOT NULL,
    PASSWORD_USER   VARCHAR(50) NOT NULL,
    WALLET   FLOAT(10.2) NOT NULL
);

CREATE TABLE TRANSACTIONS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    AMOUNT FLOAT (10.2) NOT NULL,
    ID_ORIGIN   INT NOT NULL,
    ID_DEST INT NOT NULL
);

ALTER TABLE TRANSACTIONS
ADD FOREIGN KEY (ID_ORIGIN) REFERENCES USERS(ID);

ALTER TABLE TRANSACTIONS
ADD FOREIGN KEY (ID_DEST) REFERENCES USERS(ID);

INSERT INTO TRANSACTIONS (Amount, ID_ORIGIN, ID_DEST) VALUES (1000.12, 1, 4) 

INSERT INTO USERS (NAME_USER, TYPE_USER, CPF, CNPJ, EMAIL, PASSWORD_USER, WALLET) VALUES ('ANDERSON', 'comum', '123.123.123-90', NULL, 'anderson@gmail.com', '123456', 200.10);
INSERT INTO USERS (NAME_USER, TYPE_USER, CPF, CNPJ, EMAIL, PASSWORD_USER, WALLET) VALUES ('MARIA', 'comum', '444.123.123-90', NULL, 'maria@gmail.com', '444444', 800.10);


